# Generated by Django 2.2.1 on 2019-05-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190507_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, db_column='dept_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Department', verbose_name='department'),
        ),
    ]
