# Generated by Django 2.2.1 on 2019-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_lesson_lessonemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='theme',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='theme'),
        ),
    ]
