# Generated by Django 2.2.1 on 2019-05-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190512_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', related_query_name='employee', to='backend.Employee'),
        ),
    ]
