# Generated by Django 2.2.1 on 2019-06-01 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_group_groupemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='CoursLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courslesson', related_query_name='courslesson', to='backend.Cours')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessoncours', related_query_name='lessoncours', to='backend.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='CoursEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursemployee', related_query_name='coursemployee', to='backend.Cours')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeecours', related_query_name='employeecours', to='backend.Employee')),
            ],
        ),
    ]
