# Generated by Django 2.2.1 on 2019-06-02 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_cours_coursemployee_courslesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courslsn', related_query_name='courslsn', to='backend.Cours'),
        ),
    ]
