# Generated by Django 2.2.1 on 2019-06-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20190602_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
