export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const GET_EMPLOYEE = "GET_EMPLOYEE";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_LESSONS = "GET_LESSONS";
export const GET_LESSON = "GET_LESSON";
export const DELETE_LESSON = "DELETE_LESSON";
export const ADD_LESSON = "ADD_LESSON";
export const UPDATE_LESSON = "UPDATE_LESSON";

export const GET_LESSONS_EMPLOYEES = "GET_LESSONS_EMPLOYEES";
export const GET_LESSON_EMPLOYEE = "GET_LESSON_EMPLOYEE";
export const DELETE_LESSON_EMPLOYEE = "DELETE_LESSON_EMPLOYEE";
export const ADD_LESSON_EMPLOYEE = "ADD_LESSON_EMPLOYEE";
export const UPDATE_LESSON_EMPLOYEE = "UPDATE_LESSON_EMPLOYEE";

export const GET_USERS = "GET_USERS";

export const GET_GROUPS = "GET_GROUPS";
export const GET_GROUP = "GET_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const ADD_GROUP = "ADD_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";

export const GET_GROUPS_EMPLOYEES = "GET_GROUPS_EMPLOYEES";
export const GET_GROUP_EMPLOYEE = "GET_GROUP_EMPLOYEE";
export const DELETE_GROUP_EMPLOYEE = "DELETE_GROUP_EMPLOYEE";
export const ADD_GROUP_EMPLOYEE = "ADD_GROUP_EMPLOYEE";
export const UPDATE_GROUP_EMPLOYEE = "UPDATE_GROUP_EMPLOYEE";

export const GET_COURSES = "GET_COURSES";
export const GET_COURS = "GET_COURS";
export const DELETE_COURS = "DELETE_COURS";
export const ADD_COURS = "ADD_COURS";
export const UPDATE_COURS = "UPDATE_COURS";

export const GET_COURSES_LESSONS = "GET_COURSES_LESSONS";
export const GET_COURS_LESSON = "GET_COURS_LESSON";
export const DELETE_COURS_LESSON = "DELETE_COURS_LESSON";
export const ADD_COURS_LESSON = "ADD_COURS_LESSON";
export const UPDATE_COURS_LESSON = "UPDATE_COURS_LESSON";

export const GET_COURSES_EMPLOYEES = "GET_COURSES_EMPLOYEES";
export const GET_COURS_EMPLOYEE = "GET_COURS_EMPLOYEE";
export const DELETE_COURS_EMPLOYEE = "DELETE_COURS_EMPLOYEE";
export const ADD_COURS_EMPLOYEE = "ADD_COURS_EMPLOYEE";
export const UPDATE_COURS_EMPLOYEE = "UPDATE_COURS_EMPLOYEE";